"""empty message

Revision ID: 964bca853b44
Revises: 
Create Date: 2021-07-01 23:05:18.342752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "964bca853b44"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
